create table weatherdb.weather (cityId char(6) not null primary key, cityName varchar(12), updateDate datetime);
create table weatherdb.forecast (cityId char(6) not null, dateLabel char(3) not null, dateText varchar(10), telop varchar(4), minTemperature varchar(2), maxTemperature varchar(2), imageUrl varchar(43), primary key(cityId, dateLabel));
create table weatherdb.city_master (cityId char(6) not null primary key, cityName varchar(10) not null);
insert into weatherdb.city_master values('011000', '北海道 道北 稚内');
insert into weatherdb.city_master values('012010', '北海道 道北 旭川');
insert into weatherdb.city_master values('012020', '北海道 道北 留萌');
insert into weatherdb.city_master values('013010', '北海道 道東 網走');
insert into weatherdb.city_master values('013020', '北海道 道東 北見');
insert into weatherdb.city_master values('013030', '北海道 道東 紋別');
insert into weatherdb.city_master values('014010', '北海道 道東 根室');
insert into weatherdb.city_master values('014020', '北海道 道東 釧路');
insert into weatherdb.city_master values('014030', '北海道 道東 帯広');
insert into weatherdb.city_master values('015010', '北海道 道南 室蘭');
insert into weatherdb.city_master values('015020', '北海道 道南 浦河');
insert into weatherdb.city_master values('016010', '北海道 道央 札幌');
insert into weatherdb.city_master values('016020', '北海道 道央 岩見沢');
insert into weatherdb.city_master values('016030', '北海道 道央 倶知安');
insert into weatherdb.city_master values('017010', '北海道 道南 函館');
insert into weatherdb.city_master values('017020', '北海道 道南 江差');
insert into weatherdb.city_master values('020010', '青森県 青森');
insert into weatherdb.city_master values('020020', '青森県 むつ');
insert into weatherdb.city_master values('020030', '青森県 八戸');
insert into weatherdb.city_master values('030010', '岩手県 盛岡');
insert into weatherdb.city_master values('030020', '岩手県 宮古');
insert into weatherdb.city_master values('030030', '岩手県 大船渡');
insert into weatherdb.city_master values('040010', '宮城県 仙台');
insert into weatherdb.city_master values('040020', '宮城県 白石');
insert into weatherdb.city_master values('050010', '秋田県 秋田');
insert into weatherdb.city_master values('050020', '秋田県 横手');
insert into weatherdb.city_master values('060010', '山形県 山形');
insert into weatherdb.city_master values('060020', '山形県 米沢');
insert into weatherdb.city_master values('060030', '山形県 酒田');
insert into weatherdb.city_master values('060040', '山形県 新庄');
insert into weatherdb.city_master values('070010', '福島県 福島');
insert into weatherdb.city_master values('070020', '福島県 小名浜');
insert into weatherdb.city_master values('070030', '福島県 若松');
insert into weatherdb.city_master values('080010', '茨城県 水戸');
insert into weatherdb.city_master values('080020', '茨城県 土浦');
insert into weatherdb.city_master values('090010', '栃木県 宇都宮');
insert into weatherdb.city_master values('090020', '栃木県 大田原');
insert into weatherdb.city_master values('100010', '群馬県 前橋');
insert into weatherdb.city_master values('100020', '群馬県 みなかみ');
insert into weatherdb.city_master values('110010', '埼玉県 さいたま');
insert into weatherdb.city_master values('110020', '埼玉県 熊谷');
insert into weatherdb.city_master values('110030', '埼玉県 秩父');
insert into weatherdb.city_master values('120010', '千葉県 千葉');
insert into weatherdb.city_master values('120020', '千葉県 銚子');
insert into weatherdb.city_master values('120030', '千葉県 館山');
insert into weatherdb.city_master values('130010', '東京都 東京');
insert into weatherdb.city_master values('130020', '東京都 大島');
insert into weatherdb.city_master values('130030', '東京都 八丈島');
insert into weatherdb.city_master values('130040', '東京都 父島');
insert into weatherdb.city_master values('140010', '神奈川県 横浜');
insert into weatherdb.city_master values('140020', '神奈川県 小田原');
insert into weatherdb.city_master values('150010', '新潟県 新潟');
insert into weatherdb.city_master values('150020', '新潟県 長岡');
insert into weatherdb.city_master values('150030', '新潟県 高田');
insert into weatherdb.city_master values('150040', '新潟県 相川');
insert into weatherdb.city_master values('160010', '富山県 富山');
insert into weatherdb.city_master values('160020', '富山県 伏木');
insert into weatherdb.city_master values('170010', '石川県 金沢');
insert into weatherdb.city_master values('170020', '石川県 輪島');
insert into weatherdb.city_master values('180010', '福井県 福井');
insert into weatherdb.city_master values('180020', '福井県 敦賀');
insert into weatherdb.city_master values('190010', '山梨県 甲府');
insert into weatherdb.city_master values('190020', '山梨県 河口湖');
insert into weatherdb.city_master values('200010', '長野県 長野');
insert into weatherdb.city_master values('200020', '長野県 松本');
insert into weatherdb.city_master values('200030', '長野県 飯田');
insert into weatherdb.city_master values('210010', '岐阜県 岐阜');
insert into weatherdb.city_master values('210020', '岐阜県 高山');
insert into weatherdb.city_master values('220010', '静岡県 静岡');
insert into weatherdb.city_master values('220020', '静岡県 網代');
insert into weatherdb.city_master values('220030', '静岡県 三島');
insert into weatherdb.city_master values('220040', '静岡県 浜松');
insert into weatherdb.city_master values('230010', '愛知県 名古屋');
insert into weatherdb.city_master values('230020', '愛知県 豊橋');
insert into weatherdb.city_master values('240010', '三重県 津');
insert into weatherdb.city_master values('240020', '三重県 尾鷲');
insert into weatherdb.city_master values('250010', '滋賀県 大津');
insert into weatherdb.city_master values('250020', '滋賀県 彦根');
insert into weatherdb.city_master values('260010', '京都府 京都');
insert into weatherdb.city_master values('260020', '京都府 舞鶴');
insert into weatherdb.city_master values('270000', '大阪府 大阪');
insert into weatherdb.city_master values('280010', '兵庫県 神戸');
insert into weatherdb.city_master values('280020', '兵庫県 豊岡');
insert into weatherdb.city_master values('290010', '奈良県 奈良');
insert into weatherdb.city_master values('290020', '奈良県 風屋');
insert into weatherdb.city_master values('300010', '和歌山県 和歌山');
insert into weatherdb.city_master values('300020', '和歌山県 潮岬');
insert into weatherdb.city_master values('310010', '鳥取県 鳥取');
insert into weatherdb.city_master values('310020', '鳥取県 米子');
insert into weatherdb.city_master values('320010', '島根県 松江');
insert into weatherdb.city_master values('320020', '島根県 浜田');
insert into weatherdb.city_master values('320030', '島根県 西郷');
insert into weatherdb.city_master values('330010', '岡山県 岡山');
insert into weatherdb.city_master values('330020', '岡山県 津山');
insert into weatherdb.city_master values('340010', '広島県 広島');
insert into weatherdb.city_master values('340020', '広島県 庄原');
insert into weatherdb.city_master values('350010', '山口県 下関');
insert into weatherdb.city_master values('350020', '山口県 山口');
insert into weatherdb.city_master values('350030', '山口県 柳井');
insert into weatherdb.city_master values('350040', '山口県 萩');
insert into weatherdb.city_master values('360010', '徳島県 徳島');
insert into weatherdb.city_master values('360020', '徳島県 日和佐');
insert into weatherdb.city_master values('370000', '香川県 高松');
insert into weatherdb.city_master values('380010', '愛媛県 松山');
insert into weatherdb.city_master values('380020', '愛媛県 新居浜');
insert into weatherdb.city_master values('380030', '愛媛県 宇和島');
insert into weatherdb.city_master values('390010', '高知県 高知');
insert into weatherdb.city_master values('390020', '高知県 室戸岬');
insert into weatherdb.city_master values('390030', '高知県 清水');
insert into weatherdb.city_master values('400010', '福岡県 福岡');
insert into weatherdb.city_master values('400020', '福岡県 八幡');
insert into weatherdb.city_master values('400030', '福岡県 飯塚');
insert into weatherdb.city_master values('400040', '福岡県 久留米');
insert into weatherdb.city_master values('410010', '佐賀県 佐賀');
insert into weatherdb.city_master values('410020', '佐賀県 伊万里');
insert into weatherdb.city_master values('420010', '長崎県 長崎');
insert into weatherdb.city_master values('420020', '長崎県 佐世保');
insert into weatherdb.city_master values('420030', '長崎県 厳原');
insert into weatherdb.city_master values('420040', '長崎県 福江');
insert into weatherdb.city_master values('430010', '熊本県 熊本');
insert into weatherdb.city_master values('430020', '熊本県 阿蘇乙姫');
insert into weatherdb.city_master values('430030', '熊本県 牛深');
insert into weatherdb.city_master values('430040', '熊本県 人吉');
insert into weatherdb.city_master values('440010', '大分県 大分');
insert into weatherdb.city_master values('440020', '大分県 中津');
insert into weatherdb.city_master values('440030', '大分県 日田');
insert into weatherdb.city_master values('440040', '大分県 佐伯');
insert into weatherdb.city_master values('450010', '宮崎県 宮崎');
insert into weatherdb.city_master values('450020', '宮崎県 延岡');
insert into weatherdb.city_master values('450030', '宮崎県 都城');
insert into weatherdb.city_master values('450040', '宮崎県 高千穂');
insert into weatherdb.city_master values('460010', '鹿児島県 鹿児島');
insert into weatherdb.city_master values('460020', '鹿児島県 鹿屋');
insert into weatherdb.city_master values('460030', '鹿児島県 種子島');
insert into weatherdb.city_master values('460040', '鹿児島県 名瀬');
insert into weatherdb.city_master values('471010', '沖縄県 那覇');
insert into weatherdb.city_master values('471020', '沖縄県 名護');
insert into weatherdb.city_master values('471030', '沖縄県 久米島');
insert into weatherdb.city_master values('472000', '沖縄県 南大東');
insert into weatherdb.city_master values('473000', '沖縄県 宮古島');
insert into weatherdb.city_master values('474010', '沖縄県 石垣島');
insert into weatherdb.city_master values('474020', '沖縄県 与那国島');
